export const productTypes = [
  {
    label: "Ռեագենտ",
    id: "reagent",
    showInProductsModal: true,
  },
  {
    label: "Պարագա",
    id: "consumable",
    showInProductsModal: true,
  },
  {
    label: "Հետազոտություն",
    id: "test",
    showInProductsModal: false,
  },
];

export const storages = [
  { label: "ԱԼՊ(1)", id: "1" },
  { label: "ԱՌԼ(2)", id: "2" },
  { label: "խոտանված ապրանքներ (3)", id: "3", disabled: true },
];

export const storagesData = [
  { label: "ԱԼՊ", id: "1" },
  { label: "ԱՌԼ", id: "2" },
  { label: "խոտանված ապրանքներ", id: "3" },
  { label: "Հիմնական պահեստ", id: "4" },
];

export const TestDeviceNames = [
  { label: "Cobas integra 400+", id: "Cobas integra 400+" },
  { label: "Bio tec", id: "Bio tec" },
  { label: "HumaLyzer Primus", id: "HumaLyzer Primus" },
  { label: "Stago start  4", id: "Stago start  4" },
  { label: "HumaLyte Plus 5", id: "HumaLyte Plus 5" },
  { label: "Sysmex  SN450", id: "Sysmex  SN450" },
  { label: "HumaSRate 24PT", id: "HumaSRate 24PT" },
  { label: "Manual", id: "Manual" },
  { label: "Start fax", id: "Start fax" },
];

export const productUnits = {
  arm: [
    { label: "Գր", value: "Գր" },
    { label: "Մգր", value: "Մգր" },
    { label: "Մլ", value: "Մլ" },
    { label: "Կգ", value: "Կգ" },
    { label: "Լիտր", value: "Լիտր" },
    { label: "Մմոլ/լ", value: "Մմոլ/լ" },
    { label: "Մ/լ", value: "Մ/լ" },
    { label: "Մկմոլ/լ", value: "Մկմոլ/լ" },
    { label: "Գ/լ", value: "Գ/լ" },
    { label: "Հատ", value: "Հատ" },
    { label: "Շիշ", value: "Շիշ" },
    { label: "Տուփ", value: "Տուփ" },
    { label: "Փաթեթ", value: "Փաթեթ" },
    { label: "թեսթ", value: "թեսթ" },
    { label: "Սրվակ", value: "Սրվակ" },
    { label: "Զույգ", value: "Զույգ" },
    { label: "Հավաքածու", value: "Հավաքածու" },
    { label: "Պարկ", value: "Պարկ" },
    { label: "Կասետ", value: "Կասետ" },
    { label: "Գլան փաթեթ", value: "Գլան փաթեթ" },
    { label: "Արկղ", value: "Արկղ" },
    { label: "Թեսթ հավաքածու", value: "Թեսթ հավաքածու" },
  ],
  en: [
    { label: "g", value: "Գր" },
    { label: "mg", value: "Մգր" },
    { label: "ml", value: "Մլ" },
    { label: "kg", value: "Կգ" },
    { label: "liter", value: "Լիտր" },
    { label: "mmol/l", value: "Մմոլ/լ" },
    { label: "U/l", value: "Մ/լ" },
    { label: "mkmol/l", value: "Մկմոլ/լ" },
    { label: "g/l", value: "Գ/լ" },
    { label: "pcs", value: "Հատ" },
    { label: "bottle", value: "Շիշ" },
    { label: "box", value: "Տուփ" },
    { label: "packages", value: "Փաթեթ" },
    { label: "test", value: "թեսթ" },
    { label: "vial", value: "Սրվակ" },
    { label: "couple", value: "Զույգ" },
    { label: "collection", value: "Հավաքածու" },
    { label: "a bag", value: "Պարկ" },
    { label: "cassette", value: "Կասետ" },
    { label: "roll-pack", value: "Գլան փաթեթ" },
    { label: "big box", value: "Արկղ" },
    { label: "test set", value: "Թեսթ հավաքածու" },
  ],
};

export const productPackingTypes = {
  arm: [
    { label: "Հատ", value: "Հատ" },
    { label: "Շիշ", value: "Շիշ" },
    { label: "Տուփ", value: "Տուփ" },
    { label: "Փաթեթ", value: "Փաթեթ" },
    { label: "Թեսթ", value: "թեսթ" },
    { label: "Թեսթ հավաքածու", value: "Թեսթ հավաքածու" },
    { label: "Սրվակ", value: "սրվակ" },
    { label: "Զույգ", value: "զույգ" },
    { label: "Հավաքածու", value: "հավաքածու" },
    { label: "Պարկ", value: "պարկ" },
    { label: "Կասետ", value: "կասետ" },
    { label: "Գլան փաթեթ", value: "գլան փաթեթ" },
    { label: "Արկղ", value: "արկղ" },
  ],
  en: [
    { label: "pcs", value: "Հատ" },
    { label: "bottle", value: "Շիշ" },
    { label: "box", value: "Տուփ" },
    { label: "packages", value: "Փաթեթ" },
    { label: "test", value: "թեսթ" },
    { label: "test set", value: "Թեսթ հավաքածու" },
    { label: "vial", value: "սրվակ" },
    { label: "couple", value: "զույգ" },
    { label: "collection", value: "հավաքածու" },
    { label: "a bag", value: "պարկ" },
    { label: "cassette", value: "կասետ" },
    { label: "roll-pack", value: "գլան փաթեթ" },
    { label: "big box", value: "արկղ" },
  ],
};
